FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["InThePocket.Assignment.GardenManager.Ports/InThePocket.Assignment.GardenManager.Ports.csproj", "InThePocket.Assignment.GardenManager.Ports/"]
COPY ["InThePocket.Assignment.GardenManager.Application/InThePocket.Assignment.GardenManager.Application.csproj", "InThePocket.Assignment.GardenManager.Application/"]
COPY ["InThePocket.Assignment.GardenManager.Contracts/InThePocket.Assignment.GardenManager.Contracts.csproj", "InThePocket.Assignment.GardenManager.Contracts/"]

RUN dotnet restore "InThePocket.Assignment.GardenManager.Ports/InThePocket.Assignment.GardenManager.Ports.csproj"

COPY . .
WORKDIR "/src/InThePocket.Assignment.GardenManager.Ports"

RUN dotnet build "InThePocket.Assignment.GardenManager.Ports.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "InThePocket.Assignment.GardenManager.Ports.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InThePocket.Assignment.GardenManager.Ports.dll"]