<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InThePocket.Assignment.GardenManager.Contracts\InThePocket.Assignment.GardenManager.Contracts.csproj" />
    </ItemGroup>

</Project>
